stages:
  - build
  - deploy

criar_imagens:
  stage: build
  tags:
    - aws
  script:
  - docker build -t andersonvm/app-bootcamp-devops:1.0 app/.
  - docker push andersonvm/app-bootcamp-devops:1.0

executar_imagens:
  stage: deploy
  needs:
    - criar_imagens
  tags:
    - aws
  script:
  - docker container run -dti --name web-server -p 80:80 andersonvm/app-bootcamp-devops:1.0